name: Changesets

on: [pull_request]
jobs:
  changeset_present:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Extract branch name
        id: extract_branch
        run: |
          echo "test: $GITHUB_HEAD_REF"
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      - name: Changeset file lookup  
        env:
          GH_TOKEN: ${{ github.token }}
          PR_BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: |
          echo "$PR_BRANCH"
          files=$(gh pr diff --name-only)
          if [[ $files =~ \.changeset\/.*.md ]]; then
            echo "Changesets found!"
          else
            echo "There is no changeset file in your pull request."
            exit 1
          fi
